name: Check multiple platforms

on:
  pull_request:
    types: [ labeled ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-targets:
    if: ${{ github.event.label.name == 'ready-to-merge' }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install stable toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Run cargo check
      run: cargo check --all --features=sync
