name: Check multiple toolchains

on:
  pull_request:
    types: [ labeled ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-toolchains:
    if: ${{ github.event.label.name == 'ready-to-merge' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust-toolchain: [stable, nightly]
    steps:
    - uses: actions/checkout@v4
    - name: Install ${{ matrix.rust-toolchain }} toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ matrix.rust-toolchain }}
    - name: Run cargo check
      run: cargo check --all --features=sync
