name: Check multiple targets

on:
  pull_request:
    types: [ labeled ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-targets:
    if: ${{ github.event.label.name == 'ready-to-merge' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
        - i686-pc-windows-gnu
        - i686-pc-windows-msvc
        - i686-unknown-linux-gnu
        - x86_64-apple-darwin
        - x86_64-pc-windows-gnu
        - x86_64-pc-windows-msvc
        - x86_64-unknown-linux-gnu
        - wasm32-unknown-unknown
    steps:
    - uses: actions/checkout@v4
    - name: Install stable toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        target: ${{ matrix.target }}
    - name: Run cargo check
      run: cargo check --all --features=sync
