name: Fast PR check

on:
  pull_request:
    types: [ opened, edited ]
    branches: [ main ]
    paths: 
      - '**.rs'
      - '**/Cargo.toml'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install stable toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Run cargo test
      run: cargo test --all --features=sync
