name: Security audit

on:
  pull_request:
    types: [ labeled ]
    branches: [ main ]
    paths:
      - '**/Cargo.toml'

env:
  CARGO_TERM_COLOR: always

jobs:
  security_audit:
    if: ${{ github.event.label.name == 'ready-to-merge' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/audit@v1
      with:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
