name: Test feature permutations

on:
  pull_request:
    types: [ labeled ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-features:
    if: ${{ github.event.label.name == 'ready-to-merge' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        std: ["", "alloc,", "std,"]
        sync: ["", "sync,"]
        nightly: ["", "nightly,"]
    steps:
    - uses: actions/checkout@v2
    - name: Install nightly toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
    - name: Run cargo check
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all --features=${{ matrix.std }}${{ matrix.sync }}${{ matrix.nightly }}
